version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "6000:5432"
    volumes:
      - ./docker-data/postgresql:/var/lib/postgresql/data
      - ./db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
    environment:
      POSTGRES_PASSWORD: example